### ISSUE TITLE
Fail to run build command

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webui#2]
I don't know how to explain my error so here my traceback: [traceback.txt](https://github.com/airdcpp-web/airdcpp-webui/files/391461/traceback.txt)

**Comment by maksis** [comment]
Hmm... could you first try [upgrading to npm 3](https://docs.npmjs.com/getting-started/installing-node) and making a fresh install after that?

**Comment by Kcchouette** [comment]
So at first I had node v4.4.7 and npm v2.15.8. 

Now I have v4.4.7 and npm v3.10.5
I still have npm warning but it's building so closing this issue.
Thanks!
